[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    olikraus/U8g2 @ ^2.35.19

[env:esp32dev]
upload_speed = 921600
build_flags =
    -D CORE_DEBUG_LEVEL=0

[env:ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = // replace with your ESP32 IP
upload_flags =
    --progress
     --auth= // replace with your ESP32 OTA password
