[platformio]
default_envs = esp32dev_ota

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    sandeepmistry/LoRa @ 0.8.0
    olikraus/U8g2 @ 2.36.5

[env:esp32dev_usb]
upload_protocol = esptool

[env:esp32dev_ota]
upload_protocol = espota
upload_port = 192.168.1.122 ; Replace with device IP (e.g., 192.168.1.100) if mDNS fails
