[env]
build_flags =
	-I include
	-I src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
	sandeepmistry/LoRa @ ^0.8.0
	olikraus/U8g2 @ ^2.35.19
build_flags =
	${env.build_flags}
	-D CORE_DEBUG_LEVEL=0

[env:ota]
extends = env:esp32dev
upload_protocol = espota
upload_port =
upload_flags =
	--progress
	--auth=${sysenv.LORA_CW_OTA_PASSWORD}

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
	+<crypto/>
	+<protocol/>
	+<morse/>
build_flags =
	${env.build_flags}
	-std=gnu++17
	-lmbedtls
	-lmbedcrypto
	-lmbedx509
